name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build package
        run: pnpm run build

      # - name: Test
      #   run: pnpm test

      - name: Publish package
        run: |
          if [ -n "${{ secrets.NPM_ORG }}" ]; then
            pnpm publish --access public --scope=${{ secrets.NPM_ORG }}
          else
            pnpm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
